# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'git://github.com/puppetlabs/provision.git'
  forge_modules:
    augeas_core: "puppetlabs/augeas_core"
    yumrepo_core: "puppetlabs/yumrepo_core"
    yumrepo_core: "puppetlabs/yumrepo_core"
    inifile: "puppetlabs/inifile"
    apt: "puppetlabs/apt"
    registry: "puppetlabs/registry"
    stdlib: "puppetlabs/stdlib"
    concat: "puppetlabs/concat"
  symlinks:
    duo_unix: "#{source_dir}"

